version: "3.1"

services:
  mysql:
    container_name: mysql
    restart: always
    image: mysql:8.0
    hostname: mysql
    command: --default-authentication-plugin=mysql_native_password    
    ports:
        - "33006:3306"
    volumes:
        - ./db-data/:/var/lib/mysql/
        # - ./docker/db-conf/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
        - MYSQL_ROOT_PASSWORD=secret
        - MYSQL_DATABASE=app_database
        - MYSQL_ALLOW_EMPTY_PASSWORD=no
        - MYSQL_USER=user
        - MYSQL_PASSWORD=secret
  www:
    build: ./docker/itc-php81-apache
    image: itconquest/php81-apache:latest
    container_name: app_www
    depends_on: [mysql]
    restart: always
    hostname: app_www
    expose:
        - "80"
    ports:
      - 8800:80        
    volumes:
        - ./:/var/www/html
        - ./docker/vhost.conf/:/etc/apache2/sites-available/000-default.conf
        # - ./php-conf/php_overrides.ini:/usr/local/etc/php/conf.d/php_overrides.ini
    environment:
        - VIRTUAL_HOST=app_www.com
    # labels:
    #   deck-chores.job1.command: sh -c "cd /var/www/html && php artisan schedule:run &> /proc/1/fd/1"
    #   deck-chores.job1.cron: '* * * * * * * 0' # every minute

  phpmyadmin:
    image: beeyev/phpmyadmin-lightweight:latest
    links:
      - mysql
    environment:
      # TZ: UTC
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: secret
    restart: unless-stopped
    depends_on: [mysql]
    ports:
      - 8089:80    

  # scheduler:
  #     image: funkyfuture/deck-chores:1
  #     restart: unless-stopped
  #     environment:
  #       TIMEZONE: Asia/Dhaka
  #     volumes:
  #       - /var/run/docker.sock:/var/run/docker.sock

# networks:
#     itconquest:
#         external: true
