version: "3.1"

services:
  rabbitmq:
    image: rabbitmq:3.10-management
    # image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    restart: unless-stopped
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./conf/data/:/var/lib/rabbitmq/
        - ./conf/log/:/var/log/rabbitmq
    environment:
        - RABBITMQ_DEFAULT_USER=admin
        - RABBITMQ_DEFAULT_PASS=secret
#     networks:
#         - itconquest

# networks:
#     itconquest:
#         external: true

    networks:
    - laravel-boilerplate_default

networks:
    laravel-boilerplate_default:
        external: true